### ISSUE TITLE
Set image to contain

### ISSUE THREAD

**Issue by maghffu** [samjonesigd/vue-image-zoomer#12]
How to set image fit to contain?

**Comment by samjonesigd** [comment]
@maghffu use the img-class prop and make a class to be 100% width or max-width 100%

**Comment by maghffu** [comment]
I want fit height, i set max-height to 100% but doesn't work

**Comment by samjonesigd** [comment]
@maghffu is your image smaller than the height of the container?

**Comment by maghffu** [comment]
no, my image is larger than the height of container

**Comment by maghffu** [comment]
it work if i use px, but doesn't work when i use calc(100% - 130px)

**Comment by samjonesigd** [comment]
@maghffu does your container have a height without an image in it? I'm pretty sure this is a css problem.

**Comment by maghffu** [comment]
my image source from base_64 format, it causing problem?

**Comment by samjonesigd** [comment]
@maghffu its a little bit hacky but can be done with css

https://codesandbox.io/s/cool-flower-jy9u3?file=/src/App.vue

when you set a max height of an image with a percentage the container needs to have a set height, and there's containers in the component.

I recommend working with widths instead of heights for images.
